title: are we decentralized yet?
author: Jackson Palmer
email: inquiries@ummjackson.com
description: analyzing how decentralized the top 100 cryptocurrency projects really are
baseurl: ""
url: "https://ummjackson.github.io/awdy/"

# Build settings
markdown: kramdown